import type {
  AuditEvent,
  ConsultationDraft,
  DbCategoryV2,
  DocumentRequirement,
  IntegrationTask,
  JourneyPhase,
  JourneyStep,
  MeetingDraft,
  RequestJourney,
} from '@/app/journey/types';

const now = '2026-03-10 10:00';

/** DB 카테고리 레거시→V2 변환 */
function toDbCategoryV2(legacy: string): DbCategoryV2 {
  if (legacy === 'compensation') return 'compensation';
  if (legacy === 'intro') return 'referral';
  return 'possible';
}

export const DEFAULT_CONSULTATION_DRAFT: ConsultationDraft = {
  currentStep: 'step1',
  selectedStatus: 'waiting',
  selectedReason: '',
  insuranceStatus: '있음',
  insuranceType: '실손+종합',
  monthlyPremium: '25',
  paymentStatus: '정상',
  contractor: '본인/본인',
  joinPath: '관계 없음',
  trafficAccident: '없음',
  trafficAccidentDetail: '',
  surgery: '없음',
  surgeryOptions: [],
  surgeryDetail: '',
  criticalDisease: '없음',
  criticalOptions: [],
  criticalDetail: '',
  medication: '없음',
  medicationDetail: '',
  companion: '없음',
  disposition: '중립',
  trustLevel: '보통',
  decisionMaker: '본인',
  bestTime: '무관',
  traitNote: '',
  contactAttempts: '',
  lastContactChannel: '',
  lastContactAt: '',
  nextRetryAt: '',
  holdReason: '',
  holdUntil: '',
  holdOwner: '',
  scriptExecuted: false,
  scriptQaChecked: false,
  customerReaction: '',
  customerSummary: '',
  objectionSummary: '',
  meetingFit: '',
  handoffNote: '',
  cautionNote: '',
  callRecordLink: '',
  transcriptAttached: false,
  reentryEligible: '',
  hiraReviewedBy: '',
  hiraReviewedAt: '',
  needMedicalDocs: '',
  claimOpportunityNote: '',
  simpleHandlingMode: '',
  existingContractGoal: '',
  designNeed: '',
  referralName: '',
  referralRelationship: '',
  referralBenefitExplained: false,
};

export const DEFAULT_MEETING_DRAFT: MeetingDraft = {
  selectedGroup: 'PENDING',
  selectedDetail: '',
  selectedSubDetail: '',
  meetingTime: '',
  meetingLocation: '',
  meetingConfirmed: false,
  companions: [],
  authCodeReceived: false,
  insuranceSystemRegistered: false,
  statusInputDone: false,
  dbCategory: '',
  meetingCallFormDone: false,
  designRequested: false,
  preMeetingDocReminderDone: false,
  preMeetingStrategyDone: false,
  preMeetingTomorrowNoticeSent: false,
  preMeetingReferralPushSent: false,
  preMeetingCancellationNoticeSent: false,
  onSiteEasyPaperDone: false,
  onSiteAppLinked: false,
  onSitePolicyCollected: false,
  onSitePaymentStatementCollected: false,
  onSiteInstitutionLinked: false,
  onSiteClaimAgreementDone: false,
  onSiteReferralPrompted: false,
  preCallDone: false,
  preCallNote: '',
  preCallScheduledAt: '',
  preCallLocationConfirmed: false,
  companionGuideDone: false,
  analysisFileUploaded: false,
  analysisAgenda: '',
  scriptReady: false,
  hiraSummary: '',
  meetingStarted: false,
  recordingStarted: false,
  ssnVerified: false,
  attendeeConfirmed: false,
  meetingPurposeChecked: false,
  coverageSummary: '',
  customerUnderstandingNote: '',
  designReviewStatus: 'pending',
  designReviewNote: '',
  redesignAction: '',
  contractData: [],
  contractDataCount: 0,
  contractExpectedPaymentDate: '',
  contractOwner: '',
  claimHandoffMemo: '',
  claimTransferRequested: false,
  claimTransferReason: '',
  claimTransferAt: '',
  followupDate: '',
  followupLocation: '',
  followupPurpose: '',
  arrivalChecked: false,
  callAttemptLog: '',
  alternativeProposal: '',
  withdrawalAt: '',
  postMeetingNote: '',
  referralAsked: false,
  memberSignupCompleted: false,
  hometaxLinked: false,
  hiraLinked: false,
  nhisLinked: false,
  c4uLinked: false,
  referralCount: 0,
  referralContacts: [],
  cxActionsCount: 0,
  assignmentStatus: 'unassigned',
  assignmentSource: 'manual',
  assignedTeam: '',
  assignedStaff: '',
  regionLevel1: '',
  regionLevel2: '',
  notificationState: 'pending',
  excludeState: 'active',
  excludeReason: '',
  customerErrorReportedAt: '',
  customerErrorReportedBy: '',
  gloSignRequested: false,
  gloSignSigned: false,
  easyPaperRequested: false,
  claimAgreementRequested: false,
  postResultReported: false,
  postStatusChanged: false,
  postContractInfoSaved: false,
  postThreeDocSubmitted: false,
};

function baseDocuments(): DocumentRequirement[] {
  return [
    { docCode: 'privacy-consent', label: '개인정보 수집·이용 동의', pack: 'base_consent_pack', source: 'generated', requiredWhen: '상담 진입 전', verificationState: 'verified', reviewedBy: 'System', reviewedAt: now },
    { docCode: 'policy-consent', label: '서비스 신청 동의', pack: 'base_consent_pack', source: 'generated', requiredWhen: '접수 완료 전', verificationState: 'verified', reviewedBy: 'System', reviewedAt: now },
    { docCode: 'resident-transfer-consent', label: '고유식별정보 전송 동의', pack: 'base_consent_pack', source: 'generated', requiredWhen: '심평원 조회 전', verificationState: 'verified', reviewedBy: 'System', reviewedAt: now },
  ];
}

function refundDocuments(): DocumentRequirement[] {
  return [
    { docCode: 'policy-view-consent', label: '보험 열람 동의서', pack: 'refund_claim_pack', source: 'gloSign', requiredWhen: '3년 환급 상담 완료 후', verificationState: 'sent' },
    { docCode: 'medical-record-consent', label: '진료기록 열람 동의서', pack: 'refund_claim_pack', source: 'gloSign', requiredWhen: '청구 인계 전', verificationState: 'missing' },
    { docCode: 'medical-record-poa', label: '진료기록 위임장', pack: 'refund_claim_pack', source: 'upload', requiredWhen: '청구 인계 전', verificationState: 'missing' },
    { docCode: 'claim-agreement', label: '청구대행 약정서', pack: 'refund_claim_pack', source: 'gloSign', requiredWhen: '청구 인계 전', verificationState: 'received' },
    { docCode: 'hira-original', label: '심평원 원본 PDF', pack: 'refund_claim_pack', source: 'generated', requiredWhen: '상담/미팅 검토 전', verificationState: 'verified', reviewedBy: '김상담', reviewedAt: now },
    { docCode: 'id-copy', label: '신분증 사본', pack: 'refund_claim_pack', source: 'upload', requiredWhen: '대리 청구 시', verificationState: 'missing' },
    { docCode: 'recording-proof', label: '상담/미팅 녹취', pack: 'refund_claim_pack', source: 'manual', requiredWhen: '청구 인계 전', verificationState: 'missing' },
  ];
}

function salesDocuments(): DocumentRequirement[] {
  return [
    { docCode: 'glo-sign', label: '글로싸인 전자서명', pack: 'sales_contract_pack', source: 'gloSign', requiredWhen: '계약 완료 전', verificationState: 'sent' },
    { docCode: 'comparison-confirm', label: '비교설명확인서', pack: 'sales_contract_pack', source: 'easyPaper', requiredWhen: '계약 완료 전', verificationState: 'missing' },
    { docCode: 'privacy-sales', label: '개인정보동의서', pack: 'sales_contract_pack', source: 'gloSign', requiredWhen: '계약 완료 전', verificationState: 'received' },
    { docCode: 'disclosure-duty', label: '고지의무확인서', pack: 'sales_contract_pack', source: 'gloSign', requiredWhen: '계약 완료 전', verificationState: 'missing' },
    { docCode: 'easy-paper', label: '이지페이퍼 / 모바일 청약서', pack: 'sales_contract_pack', source: 'easyPaper', requiredWhen: '계약 완료 전', verificationState: 'missing' },
    { docCode: 'monitoring', label: '완전판매 모니터링', pack: 'sales_contract_pack', source: 'manual', requiredWhen: '계약 완료 직후', verificationState: 'missing' },
  ];
}

function familyDocuments(): DocumentRequirement[] {
  return [
    { docCode: 'family-certificate', label: '가족관계증명서', pack: 'family_pack', source: 'upload', requiredWhen: '동반/타인명의 건', verificationState: 'missing' },
    { docCode: 'family-id-proof', label: '타인명의 증빙', pack: 'family_pack', source: 'upload', requiredWhen: '타인명의 카드/계좌', verificationState: 'missing' },
  ];
}

function referralDocuments(): DocumentRequirement[] {
  return [
    { docCode: 'referral-info', label: '추천인 정보 기록', pack: 'referral_pack', source: 'manual', requiredWhen: '소개 DB 상담 전', verificationState: 'missing' },
    { docCode: 'referral-benefit-guide', label: '소개 혜택 안내 기록', pack: 'referral_pack', source: 'manual', requiredWhen: '소개 유도 시', verificationState: 'missing' },
  ];
}

function buildDocuments(type: RequestJourney['journeyType']): DocumentRequirement[] {
  const docs = [...baseDocuments()];
  if (type === 'refund') docs.push(...refundDocuments());
  if (type === 'simple') docs.push(...salesDocuments());
  if (type === 'intro') docs.push(...salesDocuments(), ...referralDocuments());
  if (type === 'family') docs.push(...refundDocuments(), ...familyDocuments());
  return docs;
}

function buildIntegrations(type: RequestJourney['journeyType']): IntegrationTask[] {
  return [
    { taskCode: 'hira-sync', label: '심평원 조회', provider: 'hira', state: 'verified', externalId: 'HIRA-20260310', requestedAt: '2026-03-09 09:10', verifiedAt: '2026-03-09 09:12', reviewedBy: '김상담' },
    { taskCode: 'glo-sign-sync', label: '글로싸인 수신', provider: 'gloSign', state: type === 'refund' ? 'sent' : 'received', externalId: 'GLO-2201', requestedAt: '2026-03-09 15:20' },
    { taskCode: 'easy-paper-sync', label: '이지페이퍼 청약', provider: 'easyPaper', state: type === 'simple' || type === 'intro' ? 'requested' : 'idle', externalId: 'EASY-9911', requestedAt: '2026-03-10 10:05' },
    { taskCode: 'script-review', label: '스크립트 QA', provider: 'script', state: 'requested', requestedAt: '2026-03-10 10:20' },
    { taskCode: 'crm-kakao', label: '알림톡/CRM', provider: 'kakao', state: 'verified', requestedAt: '2026-03-10 08:30', verifiedAt: '2026-03-10 08:31' },
    { taskCode: 'claim-handoff', label: '청구 인계', provider: 'claims', state: type === 'refund' ? 'requested' : 'idle', requestedAt: '2026-03-10 11:00' },
  ];
}

function buildAudit(message: string, actor: string, type: AuditEvent['type'], tone: AuditEvent['tone'] = 'default'): AuditEvent {
  return {
    id: `${type}-${actor}-${message}`,
    type,
    message,
    actor,
    at: now,
    tone,
  };
}

export function createInitialJourneys(): RequestJourney[] {
  return [
    {
      requestId: 'R-2026-001',
      customerName: '이영희',
      journeyType: 'refund',
      owner: '김상담',
      stage: 'consultation',
      status: '1차 상담 진행',
      slaLabel: '오늘 18:00까지 인계',
      nextDueAt: '2026-03-10 18:00',
      nextAction: '상담 요약과 청구 포인트를 정리해 미팅팀으로 인계',
      notificationState: 'pending',
      currentStageStatus: {
        stageId: 'consultation',
        statusCode: '1st-complete',
        statusLabel: '1차 상담 완료',
        enteredAt: '2026-03-10 10:00',
        enteredBy: '김상담',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('refund'),
      integrationTasks: buildIntegrations('refund'),
      auditTrail: [
        buildAudit('광고 유입 접수 완료', 'System', 'status_changed', 'success'),
        buildAudit('심평원 조회 결과 검토 시작', '김상담', 'integration_updated'),
      ],
      phase: 'tm' as JourneyPhase,
      step: 'S5_first_tm' as JourneyStep,
      dbCategoryV2: 'compensation' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-09 08:00', exitedAt: '2026-03-09 08:05' },
        { step: 'S2_hira_lookup' as JourneyStep, enteredAt: '2026-03-09 08:05', exitedAt: '2026-03-09 09:12' },
        { step: 'S3_refund_apply' as JourneyStep, enteredAt: '2026-03-09 09:12', exitedAt: '2026-03-09 09:30' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-09 09:30', exitedAt: '2026-03-10 09:00' },
      ],
      consultationDraft: {
        ...DEFAULT_CONSULTATION_DRAFT,
        currentStep: 'step2',
        selectedStatus: '1st-complete',
        insuranceStatus: '있음',
        insuranceType: '실손+종합',
        monthlyPremium: '25',
        paymentStatus: '정상',
        contractor: '본인/본인',
        joinPath: '관계 없음',
        trafficAccident: '있음',
        trafficAccidentDetail: '2024-08-10 아주대병원 응급실 - 교통사고 (추돌)',
        surgery: '있음',
        surgeryOptions: ['용종', '골절'],
        surgeryDetail: '대장내시경 용종 제거, 좌측 요골 골절 이력 확인',
        medication: '있음',
        medicationDetail: '메트포르민 500mg 복용 중',
        contactAttempts: '2',
        lastContactChannel: '전화',
        lastContactAt: '2026-03-10 09:30',
        scriptExecuted: true,
        customerReaction: '긍정',
        customerSummary: '환급 가능성에 공감하며 미팅 희망',
        claimOpportunityNote: '용종 제거 및 교통사고 응급실 기록 기반 청구 포인트 존재',
      },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        selectedGroup: 'NEGOTIATING',
        selectedDetail: 'followup-2nd-meeting',
        dbCategory: 'compensation',
        meetingLocation: '서울 강남구 역삼동 테헤란로 128',
        regionLevel1: '서울',
        regionLevel2: '강남구',
      },
    },
    {
      requestId: 'R-2026-002',
      customerName: '김철수',
      journeyType: 'simple',
      owner: '박미팅',
      stage: 'meeting',
      status: '미팅 확정',
      slaLabel: '내일 오전 11:00 미팅',
      nextDueAt: '2026-03-11 11:00',
      nextAction: '유선 재확인 후 사전 분석 자료를 준비',
      notificationState: 'verified',
      currentStageStatus: {
        stageId: 'meeting',
        statusCode: 'meeting-confirmed',
        statusLabel: '미팅 확정',
        enteredAt: '2026-03-10 08:00',
        enteredBy: '박미팅',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('simple'),
      integrationTasks: buildIntegrations('simple'),
      auditTrail: [
        buildAudit('상담팀에서 미팅팀으로 인계 완료', 'System', 'handoff', 'success'),
      ],
      phase: 'meeting' as JourneyPhase,
      step: 'S8_meeting_execution' as JourneyStep,
      dbCategoryV2: 'possible' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-08 10:00', exitedAt: '2026-03-08 10:05' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-08 14:00', exitedAt: '2026-03-09 09:00' },
        { step: 'S5_first_tm' as JourneyStep, enteredAt: '2026-03-09 09:00', exitedAt: '2026-03-09 15:00' },
        { step: 'S6_second_tm' as JourneyStep, enteredAt: '2026-03-09 15:00', exitedAt: '2026-03-10 08:00' },
        { step: 'S7_pre_analysis' as JourneyStep, enteredAt: '2026-03-10 08:00', exitedAt: '2026-03-10 10:00' },
      ],
      consultationDraft: {
        ...DEFAULT_CONSULTATION_DRAFT,
        currentStep: 'step4',
        selectedStatus: 'meeting-handover',
        scriptExecuted: true,
        scriptQaChecked: true,
        customerReaction: '신중',
        customerSummary: '기존 보험 유지 여부와 비교 제안을 함께 검토 희망',
        objectionSummary: '기존 상품 해지 부담 우려',
        handoffNote: '배우자 동석 가능성 있어 결정권자 확인 필요',
        bestTime: '평일 오전',
        decisionMaker: '본인',
        simpleHandlingMode: '기존 계약 점검 후 추가 설계 제안',
        existingContractGoal: '기존 계약 유지 여부 판단',
        designNeed: '보장 공백 확인 필요',
        callRecordLink: 'https://ops.local/recording/R-2026-002-call-2',
        transcriptAttached: true,
      },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        selectedGroup: 'PENDING',
        dbCategory: 'possible',
        preCallDone: true,
        preCallNote: '미팅 일정과 준비물 안내 완료',
        preCallScheduledAt: '2026-03-11 11:00',
        preCallLocationConfirmed: true,
        companionGuideDone: true,
        meetingLocation: '서울 송파구 잠실동 올림픽로 300',
        regionLevel1: '서울',
        regionLevel2: '송파구',
        assignmentStatus: 'confirmed',
        assignmentSource: 'scheduled_auto',
        assignedTeam: '1팀',
        assignedStaff: '박미팅',
      },
    },
    {
      requestId: 'R-2026-003',
      customerName: '박지성',
      journeyType: 'simple',
      owner: '최미팅',
      stage: 'consultation',
      status: '접수 대기',
      slaLabel: '오늘 15:00까지 첫 통화',
      nextDueAt: '2026-03-10 15:00',
      nextAction: '필수 동의 확인 후 1차 상담 시도',
      notificationState: 'failed',
      currentStageStatus: {
        stageId: 'consultation',
        statusCode: 'waiting',
        statusLabel: '대기',
        enteredAt: '2026-03-10 09:00',
        enteredBy: 'System',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('simple'),
      integrationTasks: buildIntegrations('simple').map((task) => task.provider === 'hira' ? { ...task, state: 'requested', reviewedBy: undefined, verifiedAt: undefined } : task),
      auditTrail: [buildAudit('신규 배정건 확인 필요', 'System', 'status_changed')],
      phase: 'classification' as JourneyPhase,
      step: 'S4_screening' as JourneyStep,
      dbCategoryV2: 'possible' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-10 08:00', exitedAt: '2026-03-10 08:10' },
      ],
      consultationDraft: {
        ...DEFAULT_CONSULTATION_DRAFT,
        contactAttempts: '3',
        nextRetryAt: '2026-03-17 11:00',
        customerSummary: '부재 후 재통화 예약이 필요한 상태',
      },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        meetingLocation: '인천 연수구 송도동 컨벤시아대로 165',
        regionLevel1: '인천',
        regionLevel2: '연수구',
      },
    },
    {
      requestId: 'R-2026-004',
      customerName: '홍길동',
      journeyType: 'refund',
      owner: '이팀장',
      stage: 'closed',
      status: '상담 취소',
      slaLabel: '종결',
      nextDueAt: '-',
      nextAction: '재진입 가능 여부만 모니터링',
      excludeState: 'excluded',
      excludeReason: '고객 요청으로 원본 건은 제외 처리 후 재진입 가능성만 모니터링',
      currentStageStatus: {
        stageId: 'closed',
        statusCode: 'cancel',
        statusLabel: '취소',
        enteredAt: '2026-03-09 16:20',
        enteredBy: '이팀장',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('refund'),
      integrationTasks: buildIntegrations('refund'),
      auditTrail: [buildAudit('고객 단순 변심으로 종결', '이팀장', 'status_changed', 'warning')],
      phase: 'tm' as JourneyPhase,
      step: 'S5_first_tm' as JourneyStep,
      dbCategoryV2: 'possible' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-08 08:00', exitedAt: '2026-03-08 08:05' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-08 10:00', exitedAt: '2026-03-09 09:00' },
        { step: 'S5_first_tm' as JourneyStep, enteredAt: '2026-03-09 09:00', exitedAt: '2026-03-09 16:20' },
      ],
      consultationDraft: {
        ...DEFAULT_CONSULTATION_DRAFT,
        currentStep: 'step4',
        selectedStatus: 'cancel',
        selectedReason: 'customer-cancel',
        customerSummary: '가족과 상의 후 진행 중단 요청',
        callRecordLink: 'https://ops.local/recording/R-2026-004-cancel',
        transcriptAttached: true,
        reentryEligible: '가능',
      },
      meetingDraft: { ...DEFAULT_MEETING_DRAFT },
    },
    {
      requestId: 'R-2026-005',
      customerName: '장진숙',
      journeyType: 'intro',
      owner: '김더바다',
      stage: 'meeting',
      status: '소개 미팅 준비',
      slaLabel: '내일 14:00 소개 미팅',
      nextDueAt: '2026-03-11 14:00',
      nextAction: '추천인 정보와 소개 혜택 안내를 확정',
      notificationState: 'sent',
      currentStageStatus: {
        stageId: 'meeting',
        statusCode: 'followup-2nd-meeting',
        statusLabel: '2차 미팅 예정',
        enteredAt: '2026-03-10 09:40',
        enteredBy: '김더바다',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('intro'),
      integrationTasks: buildIntegrations('intro'),
      auditTrail: [buildAudit('소개 고객으로 추가 생성', 'System', 'note', 'success')],
      phase: 'meeting' as JourneyPhase,
      step: 'R5_meeting_execution' as JourneyStep,
      dbCategoryV2: 'referral' as DbCategoryV2,
      stepHistory: [
        { step: 'R1_referral_inflow' as JourneyStep, enteredAt: '2026-03-08 08:00', exitedAt: '2026-03-08 08:10' },
        { step: 'R2_hira_lookup' as JourneyStep, enteredAt: '2026-03-08 08:10', exitedAt: '2026-03-08 10:00' },
        { step: 'R3_refund_apply' as JourneyStep, enteredAt: '2026-03-08 10:00', exitedAt: '2026-03-08 14:00' },
        { step: 'R4_pre_analysis' as JourneyStep, enteredAt: '2026-03-08 14:00', exitedAt: '2026-03-09 09:00' },
      ],
      consultationDraft: {
        ...DEFAULT_CONSULTATION_DRAFT,
        currentStep: 'step4',
        selectedStatus: 'meeting-handover',
        scriptExecuted: true,
        scriptQaChecked: true,
        customerReaction: '긍정',
        customerSummary: '추천인 신뢰가 높아 후속 미팅 희망',
        objectionSummary: '수수료 구조 궁금해함',
        meetingFit: 'A',
        handoffNote: '추천인과 동일 담당자로 배정 필요',
        bestTime: '주말 오후',
        decisionMaker: '배우자',
        referralName: '이영희',
        referralRelationship: '가족',
        referralBenefitExplained: true,
        callRecordLink: 'https://ops.local/recording/R-2026-005-intro',
        transcriptAttached: true,
      },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        selectedGroup: 'NEGOTIATING',
        selectedDetail: 'followup-2nd-meeting',
        dbCategory: 'intro',
        followupDate: '2026-03-11 14:00',
        followupLocation: '서울 송파구 올림픽로 300',
        followupPurpose: '배우자 동석 후 최종 설명',
        assignmentStatus: 'confirmed',
        assignmentSource: 'manual',
        assignedTeam: '1팀',
        assignedStaff: '박미팅',
        regionLevel1: '서울',
        regionLevel2: '송파구',
      },
    },
    {
      requestId: 'R-2026-006',
      customerName: '윤서하',
      journeyType: 'refund',
      owner: '김상담',
      stage: 'consultation',
      status: '미팅 인계 대기',
      slaLabel: '오늘 17:30까지 배정',
      nextDueAt: '2026-03-16 17:30',
      nextAction: '방문 가능 지역을 확인해 미팅팀 배정',
      currentStageStatus: {
        stageId: 'consultation',
        statusCode: 'meeting-handover',
        statusLabel: '미팅 인계',
        enteredAt: '2026-03-16 10:10',
        enteredBy: '김상담',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('refund'),
      integrationTasks: buildIntegrations('refund'),
      auditTrail: [buildAudit('미팅 배정 대기 고객으로 전환', '김상담', 'handoff', 'success')],
      phase: 'tm' as JourneyPhase,
      step: 'S6_second_tm' as JourneyStep,
      dbCategoryV2: 'compensation' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-14 08:00', exitedAt: '2026-03-14 08:10' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-14 14:00', exitedAt: '2026-03-15 09:00' },
        { step: 'S5_first_tm' as JourneyStep, enteredAt: '2026-03-15 09:00', exitedAt: '2026-03-16 10:00' },
      ],
      consultationDraft: {
        ...DEFAULT_CONSULTATION_DRAFT,
        currentStep: 'step4',
        selectedStatus: 'meeting-handover',
        scriptExecuted: true,
        scriptQaChecked: true,
        customerReaction: '긍정',
        customerSummary: '분당권 미팅보다 서울 강남권 방문을 선호',
        bestTime: '평일 오전',
        callRecordLink: 'https://ops.local/recording/R-2026-006',
      },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        dbCategory: 'compensation',
        assignmentSource: 'scheduled_auto',
        meetingLocation: '서울 강남구 역삼동 테헤란로 128',
        regionLevel1: '서울',
        regionLevel2: '강남구',
      },
    },
    {
      requestId: 'R-2026-007',
      customerName: '오민재',
      journeyType: 'refund',
      owner: '최미팅',
      stage: 'meeting',
      status: '미팅 배정중',
      slaLabel: '오늘 14:00 고객 재안내',
      nextDueAt: '2026-03-16 14:00',
      nextAction: '고객과 시간 확정 후 캘린더 일정 반영',
      customerErrorReportedAt: '2026-03-16 13:10',
      customerErrorReportedBy: '최미팅',
      notificationState: 'failed',
      currentStageStatus: {
        stageId: 'meeting',
        statusCode: 'meeting-assigned',
        statusLabel: '미팅 배정중',
        enteredAt: '2026-03-16 09:20',
        enteredBy: '이관관리',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('refund'),
      integrationTasks: buildIntegrations('refund'),
      auditTrail: [buildAudit('2팀 최미팅에게 우선 배정', '이관관리', 'handoff', 'success')],
      phase: 'meeting' as JourneyPhase,
      step: 'S7_pre_analysis' as JourneyStep,
      dbCategoryV2: 'possible' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-14 08:00', exitedAt: '2026-03-14 08:10' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-14 14:00', exitedAt: '2026-03-15 09:00' },
        { step: 'S5_first_tm' as JourneyStep, enteredAt: '2026-03-15 09:00', exitedAt: '2026-03-15 16:00' },
        { step: 'S6_second_tm' as JourneyStep, enteredAt: '2026-03-15 16:00', exitedAt: '2026-03-16 09:00' },
      ],
      consultationDraft: {
        ...DEFAULT_CONSULTATION_DRAFT,
        currentStep: 'step4',
        selectedStatus: 'meeting-handover',
        bestTime: '오후 2시 이후',
        customerSummary: '분당 거주지 인근 카페 미팅 희망',
      },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        dbCategory: 'possible',
        meetingLocation: '경기 성남시 분당구 수내동 15-3',
        regionLevel1: '경기',
        regionLevel2: '성남시 분당구',
        assignmentStatus: 'assigned',
        assignmentSource: 'manual',
        assignedTeam: '2팀',
        assignedStaff: '최미팅',
        notificationState: 'failed',
        customerErrorReportedAt: '2026-03-16 13:10',
        customerErrorReportedBy: '최미팅',
      },
    },
    {
      requestId: 'R-2026-008',
      customerName: '한지우',
      journeyType: 'refund',
      owner: '김상담',
      stage: 'consultation',
      status: '미팅 인계 대기',
      slaLabel: '오늘 18:30까지 배정',
      nextDueAt: '2026-03-16 18:30',
      nextAction: '송도 권역 담당 설계사를 확인해 배정',
      currentStageStatus: {
        stageId: 'consultation',
        statusCode: 'meeting-handover',
        statusLabel: '미팅 인계',
        enteredAt: '2026-03-16 11:40',
        enteredBy: '김상담',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('refund'),
      integrationTasks: buildIntegrations('refund'),
      auditTrail: [buildAudit('방문 희망 지역 입력 완료', '김상담', 'draft_saved')],
      phase: 'tm' as JourneyPhase,
      step: 'S6_second_tm' as JourneyStep,
      dbCategoryV2: 'compensation' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-15 08:00', exitedAt: '2026-03-15 08:10' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-15 14:00', exitedAt: '2026-03-16 09:00' },
        { step: 'S5_first_tm' as JourneyStep, enteredAt: '2026-03-16 09:00', exitedAt: '2026-03-16 11:30' },
      ],
      consultationDraft: {
        ...DEFAULT_CONSULTATION_DRAFT,
        currentStep: 'step4',
        selectedStatus: 'meeting-handover',
        bestTime: '저녁 6시 이후',
        customerSummary: '퇴근 후 송도권 미팅 선호',
      },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        dbCategory: 'compensation',
        assignmentSource: 'urgent_auto',
        meetingLocation: '인천 연수구 송도동 컨벤시아대로 165',
        regionLevel1: '인천',
        regionLevel2: '연수구',
      },
    },
    {
      requestId: 'R-2026-009',
      customerName: '서다은',
      journeyType: 'refund',
      owner: '김상담',
      stage: 'consultation',
      status: '미팅 인계 대기',
      slaLabel: '오늘 16:30까지 배정',
      nextDueAt: '2026-03-16 16:30',
      nextAction: '수원 영통구 권역 우선 배정',
      currentStageStatus: {
        stageId: 'consultation',
        statusCode: 'meeting-handover',
        statusLabel: '미팅 인계',
        enteredAt: '2026-03-16 10:55',
        enteredBy: '김상담',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('refund'),
      integrationTasks: buildIntegrations('refund'),
      auditTrail: [buildAudit('방문 희망 지역 입력 완료', '김상담', 'draft_saved')],
      phase: 'tm' as JourneyPhase,
      step: 'S6_second_tm' as JourneyStep,
      dbCategoryV2: 'compensation' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-15 10:00', exitedAt: '2026-03-15 10:10' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-15 14:00', exitedAt: '2026-03-16 09:00' },
        { step: 'S5_first_tm' as JourneyStep, enteredAt: '2026-03-16 09:00', exitedAt: '2026-03-16 10:50' },
      ],
      consultationDraft: {
        ...DEFAULT_CONSULTATION_DRAFT,
        currentStep: 'step4',
        selectedStatus: 'meeting-handover',
        bestTime: '오전 10시~12시',
        customerSummary: '자택 근처 낮 시간대 미팅 원함',
      },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        dbCategory: 'compensation',
        assignmentSource: 'scheduled_auto',
        meetingLocation: '경기 수원시 영통구 영통동 청명남로 40',
        regionLevel1: '경기',
        regionLevel2: '수원시 영통구',
      },
    },
    {
      requestId: 'R-TBDH17720260313',
      customerName: '홍상엽',
      journeyType: 'simple',
      owner: '전선덕',
      stage: 'meeting',
      status: '계약완료',
      slaLabel: '미팅 후속 처리',
      nextDueAt: '2026-03-16 18:00',
      nextAction: '계약 후속 및 청구 인계 내역 확인',
      currentStageStatus: {
        stageId: 'meeting',
        statusCode: 'contract-completed',
        statusLabel: '계약완료',
        enteredAt: '2026-03-16 14:10',
        enteredBy: '전선덕',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('simple'),
      integrationTasks: buildIntegrations('simple'),
      auditTrail: [buildAudit('미팅 결과와 계약 정보 저장', '전선덕', 'status_changed', 'success')],
      phase: 'meeting' as JourneyPhase,
      step: 'S9_contract_close' as JourneyStep,
      dbCategoryV2: 'possible' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-13 08:00', exitedAt: '2026-03-13 08:10' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-13 14:00', exitedAt: '2026-03-14 09:00' },
        { step: 'S5_first_tm' as JourneyStep, enteredAt: '2026-03-14 09:00', exitedAt: '2026-03-14 15:00' },
        { step: 'S6_second_tm' as JourneyStep, enteredAt: '2026-03-14 15:00', exitedAt: '2026-03-15 09:00' },
        { step: 'S7_pre_analysis' as JourneyStep, enteredAt: '2026-03-15 09:00', exitedAt: '2026-03-16 10:00' },
        { step: 'S8_meeting_execution' as JourneyStep, enteredAt: '2026-03-16 10:00', exitedAt: '2026-03-16 14:00' },
      ],
      consultationDraft: { ...DEFAULT_CONSULTATION_DRAFT },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        selectedGroup: 'WON',
        selectedDetail: 'contract-completed',
        dbCategory: 'possible',
        meetingTime: '2026-03-16 12:00',
        meetingLocation: '경기도 광명시 광명동',
        meetingConfirmed: true,
        assignmentStatus: 'confirmed',
        assignmentSource: 'manual',
        assignedTeam: '3팀',
        assignedStaff: '김상담',
        regionLevel1: '경기',
        regionLevel2: '광명시',
        preCallDone: true,
        preCallScheduledAt: '2026-03-16 12:00',
        preCallLocationConfirmed: true,
        scriptReady: true,
        contractData: [
          {
            id: 'contract-hong-1',
            insurer: 'DB손해보험',
            contractType: '신규',
            productType: '종합보험',
            productName: 'DB 참좋은 종합보험',
            policyNumber: 'P2026-177301',
            contractor: '홍상엽',
            insuredPerson: '홍상엽',
            paymentCycle: '월납',
            premium: '230000',
            startDate: '2026-03-16',
            endDate: '2056-03-15',
            status: 'active',
            entryMethod: 'manual',
            sourceCarrier: 'DB손해보험',
            sourceFormat: 'manual',
            parseStatus: 'manual',
            parseWarnings: [],
            registeredAt: '2026-03-16 15:12',
            contractStatusLabel: '정상',
            paymentMethod: '자동이체',
          },
        ],
        contractDataCount: 1,
        contractOwner: '전선덕',
        claimTransferRequested: true,
        claimTransferAt: '2026-03-16 15:20',
        claimTransferReason: '현장 서류 확보 후 청구팀 전달',
        postMeetingNote: '설계안 설명 후 계약 1건 확정. 청구팀 전달용 서류까지 정리 완료.',
        onSiteAppLinked: true,
        onSitePolicyCollected: true,
        onSitePaymentStatementCollected: true,
        onSiteInstitutionLinked: true,
        preMeetingReferralPushSent: true,
        onSiteReferralPrompted: true,
        referralAsked: true,
        memberSignupCompleted: true,
        hometaxLinked: true,
        hiraLinked: true,
        nhisLinked: true,
        c4uLinked: true,
        referralCount: 2,
        referralContacts: [
          { id: 'ref-hong-1', name: '김민수', phone: '010-2244-1188', relationship: '직장 동료' },
          { id: 'ref-hong-2', name: '박은정', phone: '010-6632-4401', relationship: '배우자 친구' },
        ],
        gloSignRequested: true,
        gloSignSigned: true,
        easyPaperRequested: true,
        claimAgreementRequested: true,
        postResultReported: true,
        postStatusChanged: true,
        postContractInfoSaved: true,
        postThreeDocSubmitted: true,
      },
    },
    {
      requestId: 'R-TBDH22720260313',
      customerName: '강남호',
      journeyType: 'simple',
      owner: '이태윤',
      stage: 'meeting',
      status: '후속 진행',
      slaLabel: '2차 후속 조율',
      nextDueAt: '2026-03-17 15:00',
      nextAction: '고객 재확인 후 추가 제안 준비',
      currentStageStatus: {
        stageId: 'meeting',
        statusCode: 'followup-in-progress',
        statusLabel: '후속 진행',
        enteredAt: '2026-03-14 16:00',
        enteredBy: '이태윤',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('simple'),
      integrationTasks: buildIntegrations('simple'),
      auditTrail: [buildAudit('후속 미팅 메모 저장', '이태윤', 'draft_saved')],
      phase: 'meeting' as JourneyPhase,
      step: 'S8_meeting_execution' as JourneyStep,
      dbCategoryV2: 'possible' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-12 08:00', exitedAt: '2026-03-12 08:10' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-12 14:00', exitedAt: '2026-03-13 09:00' },
        { step: 'S5_first_tm' as JourneyStep, enteredAt: '2026-03-13 09:00', exitedAt: '2026-03-13 15:00' },
        { step: 'S7_pre_analysis' as JourneyStep, enteredAt: '2026-03-13 15:00', exitedAt: '2026-03-14 10:00' },
      ],
      consultationDraft: { ...DEFAULT_CONSULTATION_DRAFT },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        selectedGroup: 'NEGOTIATING',
        selectedDetail: 'followup-in-progress',
        dbCategory: 'possible',
        meetingTime: '2026-03-14 15:00',
        meetingLocation: '서울특별시 노원구 월계동',
        meetingConfirmed: true,
        assignmentStatus: 'confirmed',
        assignmentSource: 'manual',
        assignedTeam: '4팀',
        assignedStaff: '이팀장',
        regionLevel1: '서울',
        regionLevel2: '노원구',
        preCallDone: true,
        preCallScheduledAt: '2026-03-14 15:00',
        preCallLocationConfirmed: true,
        scriptReady: true,
        postMeetingNote: '기존 계약 유지 여부를 추가로 검토하기로 했고, 다음 연락 때 비교표를 다시 설명하기로 함.',
        onSiteAppLinked: true,
        onSitePolicyCollected: true,
        preMeetingReferralPushSent: true,
        referralAsked: true,
        memberSignupCompleted: true,
        hometaxLinked: true,
        hiraLinked: true,
        nhisLinked: false,
        c4uLinked: false,
        referralCount: 1,
        referralContacts: [
          { id: 'ref-kang-1', name: '이서준', phone: '010-7721-6300', relationship: '친구' },
        ],
        gloSignRequested: true,
      },
    },
    {
      requestId: 'R-TBDH18720260313',
      customerName: '김정운',
      journeyType: 'refund',
      owner: '유여름',
      stage: 'meeting',
      status: '계약완료',
      slaLabel: '후속 처리 대기',
      nextDueAt: '2026-03-17 11:00',
      nextAction: '청구 인계 및 추가 서류 확인',
      currentStageStatus: {
        stageId: 'meeting',
        statusCode: 'contract-completed',
        statusLabel: '계약완료',
        enteredAt: '2026-03-16 21:10',
        enteredBy: '유여름',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('refund'),
      integrationTasks: buildIntegrations('refund'),
      auditTrail: [buildAudit('계약 2건 등록 및 인계 준비', '유여름', 'status_changed', 'success')],
      phase: 'meeting' as JourneyPhase,
      step: 'S9_contract_close' as JourneyStep,
      dbCategoryV2: 'compensation' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-13 08:00', exitedAt: '2026-03-13 08:10' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-13 14:00', exitedAt: '2026-03-14 09:00' },
        { step: 'S5_first_tm' as JourneyStep, enteredAt: '2026-03-14 09:00', exitedAt: '2026-03-15 10:00' },
        { step: 'S6_second_tm' as JourneyStep, enteredAt: '2026-03-15 10:00', exitedAt: '2026-03-16 09:00' },
        { step: 'S8_meeting_execution' as JourneyStep, enteredAt: '2026-03-16 09:00', exitedAt: '2026-03-16 21:00' },
      ],
      consultationDraft: { ...DEFAULT_CONSULTATION_DRAFT },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        selectedGroup: 'WON',
        selectedDetail: 'contract-completed',
        dbCategory: 'compensation',
        meetingTime: '2026-03-16 20:00',
        meetingLocation: '경기도 평택시 평택동',
        meetingConfirmed: true,
        assignmentStatus: 'confirmed',
        assignmentSource: 'manual',
        assignedTeam: '4팀',
        assignedStaff: '이팀장',
        regionLevel1: '경기',
        regionLevel2: '평택시',
        preCallDone: true,
        preCallScheduledAt: '2026-03-16 20:00',
        preCallLocationConfirmed: true,
        scriptReady: true,
        contractData: [
          {
            id: 'contract-kim-1',
            insurer: '삼성화재',
            contractType: '신규',
            productType: '종합보험',
            productName: '삼성 다이렉트 종합보험',
            policyNumber: 'P2026-187401',
            contractor: '김정운',
            insuredPerson: '김정운',
            paymentCycle: '월납',
            premium: '200000',
            startDate: '2026-03-16',
            endDate: '2056-03-15',
            status: 'active',
            entryMethod: 'pasted',
            sourceCarrier: '삼성화재',
            sourceFormat: 'samsung_contract_detail',
            parseStatus: 'parsed',
            parseWarnings: [],
            registeredAt: '2026-03-16 20:38',
            contractStatusLabel: '정상',
            paymentMethod: '자동이체',
            rawPasteText: '삼성화재 계약상세 복붙 원문 예시',
          },
          {
            id: 'contract-kim-2',
            insurer: '메리츠화재',
            contractType: '신규',
            productType: '실손보험',
            productName: '메리츠 실손보험',
            policyNumber: 'P2026-187402',
            contractor: '김정운',
            insuredPerson: '김정운',
            paymentCycle: '월납',
            premium: '120000',
            startDate: '2026-03-16',
            endDate: '2046-03-15',
            status: 'active',
            entryMethod: 'manual',
            sourceCarrier: '메리츠화재',
            sourceFormat: 'manual',
            parseStatus: 'manual',
            parseWarnings: [],
            registeredAt: '2026-03-16 20:44',
            contractStatusLabel: '정상',
            paymentMethod: '자동이체',
          },
        ],
        contractDataCount: 2,
        contractOwner: '유여름',
        claimTransferRequested: true,
        claimTransferAt: '2026-03-16 21:30',
        claimTransferReason: '3종 서류 및 증권 정리 후 전달',
        postMeetingNote: '청구 포인트와 신규 설계안을 함께 설명했고 계약 2건 체결 후 청구 인계 준비 중.',
        onSiteAppLinked: true,
        onSitePolicyCollected: true,
        onSitePaymentStatementCollected: true,
        preMeetingReferralPushSent: true,
        onSiteReferralPrompted: true,
        memberSignupCompleted: true,
        hometaxLinked: true,
        hiraLinked: true,
        nhisLinked: true,
        c4uLinked: true,
        referralCount: 1,
        referralContacts: [
          { id: 'ref-kim-1', name: '최유진', phone: '010-5102-8181', relationship: '가족' },
        ],
        gloSignRequested: true,
        gloSignSigned: true,
        claimAgreementRequested: true,
        postResultReported: true,
        postStatusChanged: true,
        postContractInfoSaved: true,
      },
    },
    {
      requestId: 'R-2026-010',
      customerName: '서민지',
      journeyType: 'family',
      owner: '박청구',
      stage: 'claims',
      status: '청구 서류 검증중',
      slaLabel: '오늘 17:00까지 문서 확인',
      nextDueAt: '2026-03-18 17:00',
      nextAction: '동반신청 파생 건을 제외 처리하고 청구 서류를 검증',
      excludeState: 'active',
      excludeReason: '',
      notificationState: 'sent',
      currentStageStatus: {
        stageId: 'claims',
        statusCode: 'claim-doc-review',
        statusLabel: '청구 서류 검증중',
        enteredAt: '2026-03-18 09:20',
        enteredBy: '박청구',
      },
      missingRequirements: [],
      documentRequirements: buildDocuments('family'),
      integrationTasks: buildIntegrations('family'),
      auditTrail: [
        buildAudit('청구팀 검증 큐로 인계', 'System', 'claim', 'success'),
        buildAudit('동반신청 원본 보존 후 제외 검토 시작', '박청구', 'override'),
      ],
      phase: 'claims' as JourneyPhase,
      step: 'S12_doc_issuance' as JourneyStep,
      dbCategoryV2: 'possible' as DbCategoryV2,
      stepHistory: [
        { step: 'S1_inflow' as JourneyStep, enteredAt: '2026-03-15 08:00', exitedAt: '2026-03-15 08:10' },
        { step: 'S4_screening' as JourneyStep, enteredAt: '2026-03-15 14:00', exitedAt: '2026-03-16 09:00' },
        { step: 'S8_meeting_execution' as JourneyStep, enteredAt: '2026-03-17 10:00', exitedAt: '2026-03-17 16:30' },
        { step: 'S10_claim_receipt' as JourneyStep, enteredAt: '2026-03-18 09:00', exitedAt: '2026-03-18 09:20' },
      ],
      consultationDraft: {
        ...DEFAULT_CONSULTATION_DRAFT,
        companion: '있음',
        customerSummary: '배우자 동반 신청으로 파생된 가족 건',
      },
      meetingDraft: {
        ...DEFAULT_MEETING_DRAFT,
        selectedGroup: 'NEGOTIATING',
        selectedDetail: 'followup-in-progress',
        dbCategory: 'companion',
        meetingTime: '2026-03-17 16:30',
        meetingLocation: '서울 마포구 공덕동 마포대로 92',
        meetingConfirmed: true,
        assignmentStatus: 'confirmed',
        assignmentSource: 'manual',
        assignedTeam: '청구팀',
        assignedStaff: '박청구',
        regionLevel1: '서울',
        regionLevel2: '마포구',
        notificationState: 'verified',
        excludeState: 'excluded',
        excludeReason: '동반신청 원본은 보존하고 파생 고객만 청구 큐에서 처리',
        claimTransferRequested: true,
        claimTransferReason: '가족/동반신청 서류 검증 필요',
        claimTransferAt: '2026-03-18 09:10',
        claimHandoffMemo: '가족관계증명서, 위임장, 신분증 사본 검증 후 발급 요청 예정',
        customerErrorReportedAt: '2026-03-18 10:05',
        customerErrorReportedBy: '박청구',
        postMeetingNote: '원본 데이터 삭제 없이 제외 처리 후 청구/발급으로 넘겨야 하는 건',
      },
    },
  ];
}
